
services:
  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    environment:
      KEYCLOAK_DOMAIN: ${KC_HOSTNAME}
    container_name: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/entrypoint.sh:/etc/nginx/entrypoint.sh
    entrypoint: /etc/nginx/entrypoint.sh
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - proxy
  certbot:
    image: certbot/certbot:${CERTBOT_VERSION:-latest}
    environment:
      CERTBOT_LETSENCRYPT_EMAIL: admin@${KC_HOSTNAME}
      KEYCLOAK_DOMAIN: ${KC_HOSTNAME}
      PROD: ${PROD:-true}
    mem_limit: 50m
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >
      sh -c "
        if [ \"$PROD\" = \"true\" ]; then
          certbot certonly --non-interactive --webroot -w /var/www/certbot --email admin@${KC_HOSTNAME} -d ${KC_HOSTNAME} --agree-tos;      
        else
          certbot certonly --staging --non-interactive --webroot -w /var/www/certbot --email admin@${KC_HOSTNAME} -d ${KC_HOSTNAME} --agree-tos;
        fi
      "
    depends_on:
      - nginx

  keycloak:
    build:
      context: ./keycloak
    # command: start --optimized
    command: start-dev
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=${KC_DB_URL_HOST}
      - KC_DB_URL_DATABASE=${KC_DB_URL_DATABASE}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_HTTP_ENABLED=${KC_HTTP_ENABLED}
      - JAVA_OPTS=${JAVA_OPTS}
    networks:
      - proxy
      - internal

networks:
  internal:
  proxy:

volumes:
  nginx-html:
  nginx-acme:
  nginx-certs:
  nginx-vhost:
