version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
    networks:
      - proxy
    environment:
      - DEFAULT_EMAIL=admin@${KC_HOSTNAME}
    labels:
      - "traefik.enable=false"
      - "com.github.nginxproxy.nginx-proxy=true"
      - "com.github.nginxproxy.nginx-proxy.nginx_default_host=${KC_HOSTNAME}"
    user: "root"

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=admin@${KC_HOSTNAME}
      - ACME_CA_URI=${ACME_CA_URI:-https://acme-v02.api.letsencrypt.org/directory}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-html:/usr/share/nginx/html
      - nginx-acme:/etc/acme.sh
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
    networks:
      - proxy
    user: "root"

  keycloak:
    build:
      context: ./keycloak
    # command: start --optimized
    command: start-dev
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL_HOST=${KC_DB_URL_HOST}
      - KC_DB_URL_DATABASE=${KC_DB_URL_DATABASE}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_HTTP_ENABLED=${KC_HTTP_ENABLED}
      - KC_PROXY=${KC_PROXY}
      - KC_HOSTNAME_STRICT=${KC_HOSTNAME_STRICT}
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - JAVA_OPTS=${JAVA_OPTS}
      - VIRTUAL_HOST=${KC_HOSTNAME}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${KC_HOSTNAME}
      - LETSENCRYPT_EMAIL=${DEFAULT_EMAIL}
    networks:
      - proxy
      - internal

networks:
  internal:
  proxy:

volumes:
  nginx-html:
  nginx-acme:
  nginx-certs:
  nginx-vhost:
