
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80"
      - "443"
    volumes:
      - nginx-confd:/etc/nginx
      - nginx-certificates:/certificates
    restart: unless-stopped

  # Gets and installs letsencrypt certificates
  letsencrypt:
    build:
      context: ./docker/letsencrypt
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - nginx-certificates:/certificates
    restart: unless-stopped

  keycloak:
    build:
      context: ./keycloak
    # command: start --optimized
    command: start-dev
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=${KC_DB_URL_HOST}
      - KC_DB_URL_DATABASE=${KC_DB_URL_DATABASE}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_HTTP_ENABLED=${KC_HTTP_ENABLED}
      - JAVA_OPTS=${JAVA_OPTS}

volumes:
  nginx-confd:
  nginx-certificates:
