
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    environment:
      - DEFAULT_HOST=default
      - PROXY_ADDRESS_FORWARDING=true
      - HTTPS_METHOD=${HTTPS_METHOD:-noredirect}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
    ports:
      - "80:80"
      - "443:443"

  # Gets and installs letsencrypt certificates
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    # command: start --optimized
    command: start-dev
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=${KC_DB_URL_HOST}
      - KC_DB_URL_DATABASE=${KC_DB_URL_DATABASE}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_HOSTNAME_STRICT=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_ENABLED=${KC_HTTP_ENABLED}
      - JAVA_OPTS=${JAVA_OPTS}
      - VIRTUAL_HOST=${KC_HOSTNAME}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${KC_HOSTNAME}
      - LETSENCRYPT_EMAIL=admin@${KC_HOSTNAME}

