name: Build and Push Keycloak Image to GHCR

on:
  push:
    branches:
      - main
      - dev  # puedes agregar otras ramas si quieres

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        id: vars
        run: |
          echo "owner=sigic" >> $GITHUB_OUTPUT
          echo "image=keycloak" >> $GITHUB_OUTPUT
          echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image with multiple tags
        run: |
          docker build -t ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.branch }} \
                       -t ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.sha }} \
                       -t ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:latest \
                       -f ./keycloak/Dockerfile ./keycloak

      - name: Push all image tags
        run: |
          docker push ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.branch }}
          docker push ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.sha }}
          docker push ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:latest
