name: CI/CD - Build & Deploy SIGIC Keycloak (develop)

on:
  push:
    branches:
      - develop

jobs:
  lint-theme:
    name: Lint Keycloak theme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install linters
        run: |
          sudo apt-get update && sudo apt-get install -y npm libfreemarker-java
          npm install -g stylelint eslint stylelint-config-standard stylelint-config-prettier stylelint-config-standard-scss stylelint-scss
          
      - name: Compile and run CheckFtl to Validate .ftl templates with FreeMarker
        run: |
          mkdir -p build/classes
          javac -d build/classes -cp /usr/share/java/freemarker.jar keycloak/tools/CheckFtl.java
          find keycloak/themes/sigic/ -name '*.ftl' > ftl_files.txt
          java -cp build/classes:/usr/share/java/freemarker.jar tools.CheckFtl $(cat ftl_files.txt)

      - name: Lint CSS
        run: stylelint "keycloak/themes/sigic/**/*.css" --config keycloak/stylelint.config.js

      - name: Lint JS
        run: eslint "keycloak/themes/sigic/**/*.js"

  build-and-test:
    name: Build SIGIC Keycloak image (develop)
    needs: lint-theme
    runs-on: [self-hosted, build-develop, sigic-keycloak]
    environment: develop

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_GEOINTSIGIC_PAT }}" | docker login ghcr.io -u geointsigic --password-stdin

      - name: Set variables
        id: vars
        run: |
          echo "owner=centrogeo" >> $GITHUB_OUTPUT
          echo "image=sigic-keycloak" >> $GITHUB_OUTPUT
          echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "branch=develop" >> $GITHUB_OUTPUT

      - name: Build & tag Docker image
        run: |
          docker build \
            -t ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.branch }} \
            -t ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.sha }} \
            -f ./keycloak/Dockerfile ./keycloak
          
      - name: Run smoke test
        run: |
          docker run -d --rm --name test-keycloak \
            -e KC_DB=postgres \
            -e KC_DB_URL_HOST=${{ secrets.KC_DB_URL_HOST }} \
            -e KC_DB_URL_DATABASE=${{ secrets.KC_DB_URL_DATABASE }} \
            -e KC_DB_USERNAME=${{ secrets.KC_DB_USERNAME }} \
            -e KC_DB_PASSWORD=${{ secrets.KC_DB_PASSWORD }} \
            -e KC_HTTP_ENABLED=true \
            -p 8080:8080 \
            ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.branch }}

          for i in {1..20}; do
            curl -sSf http://localhost:8080/health/ready && break || sleep 2
          done

          docker rm -f test-keycloak || true

      - name: Push image
        run: |
          docker push ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.branch }}
          docker push ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.sha }}


  deploy:
    name: Deploy to dev server
    needs: build-and-test
    runs-on: [self-hosted, deploy-develop, sigic-keycloak]
    environment: develop

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set variables
        id: vars
        run: |
          echo "owner=centrogeo" >> $GITHUB_OUTPUT
          echo "image=sigic-keycloak" >> $GITHUB_OUTPUT
          echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "branch=develop" >> $GITHUB_OUTPUT

      - name: Docker login to GHCR
        run: echo ${{ secrets.GHCR_GEOINTSIGIC_PAT }} | docker login ghcr.io -u geointsigic --password-stdin

      - name: Reemplazar imagen en docker-compose-ghcr.yml
        run: |
          sed -i "s|ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:.*|ghcr.io/${{ steps.vars.outputs.owner }}/${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.sha }}|g" docker-compose-ghcr.yml

      - name: Docker Compose up
        run: |
          docker compose -f docker-compose-ghcr.yml down -v || true
          docker compose -f docker-compose-ghcr.yml up -d --force-recreate
        env:
          KC_DB_USERNAME: ${{ secrets.KC_DB_USERNAME }}
          KC_DB_PASSWORD: ${{ secrets.KC_DB_PASSWORD }}
          KC_DB_URL_HOST: ${{ secrets.KC_DB_URL_HOST }}
          KC_DB_URL_DATABASE: ${{ secrets.KC_DB_URL_DATABASE }}
          KC_DB: ${{ vars.KC_DB }}
          KC_HOSTNAME: ${{ vars.KC_HOSTNAME }}
          KC_HOSTNAME_STRICT: ${{ vars.KC_HOSTNAME_STRICT }}
          JAVA_OPTS: ${{ vars.JAVA_OPTS }}
          VIRTUAL_HOST: ${{ vars.KC_HOSTNAME }}
          VIRTUAL_PORT: "8080"
